# This is a basic workflow to help you get started with Actions

name: Read Jira Labels

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      issue_key:
        description: 'JA-123'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fetch-jira-labels:
    runs-on: ubuntu-latest

    steps:
    - name: Set up the environment
      env:
        JIRA_URL: ${{ secrets.JIRA_URL }}
        JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Fetch Jira issue labels
      id: fetch_labels
      run: |
        ISSUE_KEY="${{ github.event.inputs.issue_key }}"
        RESPONSE=$(curl -s -u "$JIRA_EMAIL:$JIRA_API_TOKEN" \
          -H "Content-Type: application/json" \
          "$JIRA_URL/rest/api/3/issue/$ISSUE_KEY")
        echo "Labels: $(echo $RESPONSE | jq '.fields.labels')" > labels.json
        echo "::set-output name=labels::$(echo $RESPONSE | jq -r '.fields.labels | join(",")')"
      env:
        JIRA_URL: ${{ secrets.JIRA_URL }}
        JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Display labels
      run: |
        echo "Jira Labels: ${{ steps.fetch_labels.outputs.labels }}"
